website: "Alkosto"
base_url: "https://www.alkosto.com"

search_url: "https://www.alkosto.com/search?text={query}&sort=relevance"

selectors:
  wait_for: "//div[contains(@class,'product__item__information')]"
  product: "//li[contains(@class,'ais-InfiniteHits-item')]"
  name: ".//h3[contains(@class,'product__item__top__title')]/text()"
  url: ".//@href"
  current_price: ".//span[contains(@class,'price')]/text()"
  original_price: ".//p[contains(@class,'product__price--discounts__old')]/text()"
  discount: ".//span[contains(@class,'label-offer')]/text()"